"""
Asynchronous Faculty Approval Workflow Automator
Detects rule-breaking edge cases (e.g., credit overload requests) generated by Matrix/Nexus
and automatically fires a webhook to a Faculty Dashboard for manual override.
"""

import json
import uuid
from typing import Dict, Any

class FacultyApprovalAutomator:
    """
    Acts as a middleware/interceptor.
    If a generated schedule violates a strict Codex policy (e.g. requires 25 credits),
    it halts the pipeline and generates a PENDING_OVERRIDE ticket.
    """

    def __init__(self):
        self.active_tickets = {}

    def intercept_and_flag(self, student_id: str, requested_schedule: Dict[str, Any], rule_violation: str) -> str:
        """
        Creates an approval ticket and 'fires a webhook' (simulated).
        """
        ticket_id = f"TKT-{str(uuid.uuid4())[:8].upper()}"
        
        ticket = {
            "ticket_id": ticket_id,
            "student_id": student_id,
            "status": "PENDING_FACULTY_APPROVAL",
            "rule_violated": rule_violation,
            "requested_schedule": requested_schedule,
            "webhook_fired_to": "faculty_dashboard_api/v1/tickets"
        }
        
        self.active_tickets[ticket_id] = ticket
        
        return json.dumps(ticket, indent=2)

    def simulate_faculty_decision(self, ticket_id: str, approved: bool, faculty_notes: str) -> str:
        """
        Simulates the webhook callback from the faculty dashboard.
        """
        if ticket_id not in self.active_tickets:
            return json.dumps({"error": "Ticket not found"})
            
        ticket = self.active_tickets[ticket_id]
        ticket["status"] = "APPROVED" if approved else "DENIED"
        ticket["faculty_notes"] = faculty_notes
        
        # If approved, this would trigger the Orchestrator to resume and finalize the schedule.
        ticket["next_action"] = "RESUME_PIPELINE" if approved else "HALT_AND_NOTIFY_STUDENT"
        
        return json.dumps(ticket, indent=2)


if __name__ == "__main__":
    automator = FacultyApprovalAutomator()
    
    print("--- 1. Matrix Generates a 25-Credit Schedule (Violates Codex 22-credit max) ---")
    mock_schedule = {"Semester 3": ["Course A", "Course B", "Course C", "Course D", "Course E", "Course F", "Course G"]}
    
    ticket_json = automator.intercept_and_flag("REG1001", mock_schedule, "MAX_CREDIT_LIMIT_EXCEEDED (Requested: 25, Max: 22)")
    print(ticket_json)
    
    ticket_dict = json.loads(ticket_json)
    ticket_id = ticket_dict["ticket_id"]
    
    print("\n--- 2. Faculty Reviews and Approves the Override ---")
    decision_json = automator.simulate_faculty_decision(ticket_id, approved=True, faculty_notes="Student is exceptional and can handle the load.")
    print(decision_json)
